name: C/C++ CI
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt-get install libgtest-dev
        cd lib && git submodule update --init --recursive
    - name: test
      run: make test
    - name: load-test
      run: make load-test
